language: php
php:
  - 7.0
  - 7.1
  - 7.2

install:
  - composer require satooshi/php-coveralls

before_script:
  - sudo apt install -y locales
  - sudo locale-gen pl_PL.UTF-8
  - mkdir -p build/logs

after_success:
  - php vendor/bin/coveralls -v

