language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

after_success:
  - php vendor/bin/coveralls -v

