dist: bionic

language: php

php:
  - 7.1
  - 7.2
  - 7.3

install:
  - composer require php-coveralls/php-coveralls

before_script:
  - sudo apt install -y locales
  - sudo locale-gen pl_PL.UTF-8
  - mkdir -p build/logs

after_success:
  - php vendor/bin/php-coveralls -v

