name: phpunit

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: mxschmitt/action-tmate@v3
    - name: composer update
      run: |
        composer update -o
    - name: locales
      run: |
        sudo apt install -y locales && sudo locale-gen pl_PL.UTF-8
    - name: test
      run: |
        XDEBUG_MODE=coverage vendor/bin/phpunit
    - name: coveralls
      run: |
        export COVERALLS_RUN_LOCALLY=1
        export COVERALLS_REPO_TOKEN=${{ secrets.coverallsToken }}
        composer require -W php-coveralls/php-coveralls
        php vendor/bin/php-coveralls -v
